### ISSUE TITLE
Issues from child projects

### ISSUE THREAD

**Issue by rogerjak** [masweetman/issue_charts#10]
Hi, thanks for a great plugin!

However, our Redmine is setup mainly with project hierarchy, and it seems that issue_charts don't care about issues from child projects.
Is it possible to add an option when creating a chart wether to include issues from child projects or not?

Thanks!
Roger

**Comment by masweetman** [comment]
Yes, I'll work on that feature. Thanks!

**Comment by masweetman** [comment]
Charts now include issues from child projects if the Redmine setting 'display_subprojects_issues' is true. Thanks for the feedback!

**Comment by rogerjak** [comment]
Thanks, tried the new version and it works, somehow.
It looks like it only include child projects in one level and not recursively, is that correct?
Is it possible to make it use all issues, like the ones that gets listed in the issue tables?

**Comment by masweetman** [comment]
Ah, I forgot about sub-sub-projects. I'll work on that too.

**Comment by masweetman** [comment]
Done. You can go ahead and update now--charts will include issues from entire sub-project tree. Thanks!
