### ISSUE TITLE
French translation for the version 1.3.0

### ISSUE THREAD

**Issue by lhadjadj** [masweetman/issue_charts#14]
Hi, it is the french translation update for the **1.3.0** version.
Bye
[fr.zip](https://github.com/masweetman/issue_charts/files/442049/fr.zip)

**Comment by masweetman** [comment]
There shouldn't be any changes--the new labels are just references to labels that already exist.

**Comment by lhadjadj** [comment]
Oops, i translate it too.

Envoyé de mon iPad
