### ISSUE TITLE
Poor perfomance

### ISSUE THREAD

**Issue by peritaun** [masweetman/issue_charts#15]
Hi,

Since I have installed the new version of the plugin, the performance is poor compared with the previous one... 

When you execute the query for drawing the chart, it hangs for a while...

Tks!!

**Comment by masweetman** [comment]
If you could send your Redmine log file to mike@michaelsweetman.com, and tell me the name of the chart that's slow, I could take a look at it. I haven't been able to test with more than a few thousand issues

**Comment by masweetman** [comment]
Closing old issues. Haven't seen any performance issues.
