### ISSUE TITLE
Grouping Results by Custom Field with multiple values ends with Error 500

### ISSUE THREAD

**Issue by pkestefran** [masweetman/issue_charts#16]
Hello, I have noticed that while creating any chart type while grouping results by my custom created field with multiple values always ends with error 500. The chart is still shown in the general chart page but the specific chart can not be opened. The /edit link works so you can still edit the chart and possibly remove it.

Found on version 3.3.0

How to reproduce:
1. Create Custom Field - List - Multiple Values - Checkboxes
2. Create some issues with the Custom Field and select multiple values
3. Create a chart with the Custom Field

**Comment by masweetman** [comment]
Thanks! fixed in latest commit.

**Comment by pkestefran** [comment]
Hi, works great. Thanks.
