### ISSUE TITLE
SQLite3::SQLException: no such column

### ISSUE THREAD

**Issue by JohnnyMudcrab** [masweetman/issue_charts#19]
Hi,
i just tried out the plugin but run into an error which i'm not able to resolve on my own.
I'm running redmine 3.3.2.stable. I followed the install instructions on the github page and checked if chartkick is installed (using chartkick 2.2.2). However, when i enable the module on my project and click the charts menu entry I get an internal error. From the production.log I get the following output:

```
Processing by ChartsController#index as HTML
  Parameters: {"project_id"=>"xxx"}
  Current user: xxx (id=4)
  Rendered plugins/issue_charts/app/views/charts/_action_menu.html.erb (0.4ms)
  Rendered plugins/issue_charts/app/views/charts/index.html.erb within layouts/base (3.4ms)
Completed 500 Internal Server Error in 11ms (ActiveRecord: 2.9ms)

ActionView::Template::Error (SQLite3::SQLException: no such column: false: SELECT "charts".* FROM "charts" WHERE (project_id = 2 AND user_id = 4 AND is_public = false)  ORDER BY "charts"."name" ASC):
     5: <h2><%= l(:label_my_charts) %></h2>
     6: 
     7:   <div class="splitcontent" style="overflow:hidden;">
     8:     <% @my_charts.each do |chart| %>
     9:       <div class="<%= cycle("splitcontentleft", "splitcontentright") %>">
    10:         <h3><%= link_to chart.name, chart_path(chart) %></h3>
    11:         <%= Tracker.find(chart.tracker_id).name + ' ' + l(:label_issue_plural).downcase if chart.tracker_id > 0 %>
  plugins/issue_charts/app/views/charts/index.html.erb:8:in `_plugins_issue_charts_app_views_charts_index_html_erb__3499231962573528611_70041700'
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

It seems something went wrong with SQLite. Is there any way to resolve that issue?

kind regards
johnny

**Comment by masweetman** [comment]
You didn't migrate the database. Run bundle exec rake redmine:plugins:migrate RAILS_ENV=production

**Comment by JohnnyMudcrab** [comment]
As I said, I followed the install instructions and thus migrated the database. I migrated it again, but the error still persist. I am running a few other plugins that work fine (e.g. easy_gantt, quick_view, redmine_theme_changer ...), so the database seems to work in general. Are there any things that might have changed due to the new redmine release? I really would like to use the plugin, as it is exactly what I was looking for. Many thanks for that.

**Comment by masweetman** [comment]
It's giving you a "no such column" error, and all of those columns definitely exist in the migration. The only think I can think to do is to go into your database, drop the charts table, and try installing again. maybe you already had a table in you database called "charts". I should have named it something more unique.
