### ISSUE TITLE
Error "area_chart"

### ISSUE THREAD

**Issue by adrian013** [masweetman/issue_charts#21]
Hello,
I've installed the plugin correctly, but when I add a new Chart a get this error:

Error loading chart 'a'. undefined method `area_chart' for #<#:0x007f0495685b78>

**Comment by masweetman** [comment]
Does it work with another type of chart? If not, you may not have installed gems. Run "bundle update"

**Comment by selamisozer** [comment]
Hi
My problem continues
Error loading chart 'Grafik'. undefined method `column_chart' for #<#:0x9bfc298>

**Comment by masweetman** [comment]
Please post the error from your production log

**Comment by selamisozer** [comment]
Hi,
You can see in the attachment.

**Comment by masweetman** [comment]
This error proves that the plugin is not installed correctly: ActionController::RoutingError (No route matches [GET] "/javascripts/chartkick.js")

Try re-installing.
