### ISSUE TITLE
Problem translate menu item and Error 404

### ISSUE THREAD

**Issue by benoitlm** [masweetman/issue_charts#22]
Hi

After deploy the plugin on redmine (v3.3.2), I've got this error on item menu :

![image](https://cloud.githubusercontent.com/assets/5756348/23311732/6748f984-fab7-11e6-81fe-c8a8e8cc55c1.png)

when I click on the link, i've got "404 error" :
![image](https://cloud.githubusercontent.com/assets/5756348/23311821/b7ee8d18-fab7-11e6-989a-6a9900343087.png)

Thanks in advance for your help.

Regards,

**Comment by masweetman** [comment]
What does your production log say?

**Comment by brusguilis** [comment]
I've gotten the same error in redmine 3.3.3, the log said:

17824	ActionController::RoutingError (uninitialized constant ChartsController):
 17825	  activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:261:in `const_get'
 17826	  activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:261:in `block in constantize'
 17827	  activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `each'
 17828	  activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `inject'
 17829	  activesupport (4.2.7.1) lib/active_support/inflector/methods.rb:259:in `constantize'
 17830	  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:70:in `controller_reference'
 17831	  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:60:in `controller'
 17832	  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:39:in `serve'
 17833	  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 17834	  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `each'
 17835	  actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
 17836	  actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
 17837	  /usr/lib/ruby/vendor_ruby/rack/openid.rb:98:in `call'

**Comment by masweetman** [comment]
It looks like the plugin was not installed correctly. Make sure you migrated the database and installed all gems.
