### ISSUE TITLE
3.2.3 can not install new2.0

### ISSUE THREAD

**Issue by nateby** [masweetman/issue_charts#31]
Hi 
I use redmine 3.2.3
and redmine's ruby version is 2.1.0
When I input cmd : bundle install , it errors
groupdate needs ruby >= 2.2 , but my ruby is 2.1.0
How to solve it ? 
Thanks

**Comment by masweetman** [comment]
Support for Ruby 2.2 and earlier have ended by Ruby community.
https://www.redmine.org/projects/redmine/wiki/RedmineInstall
