### ISSUE TITLE
Error Throwing while loading Chart

### ISSUE THREAD

**Issue by meetdileep** [masweetman/issue_charts#9]
Hi,

I had installed Charts Plugin in Redmine 3.2 Version and Plugin was installing without any error. But when in Create a new chart and try to open the chart it is throwing an error as given below.

Error loading chart 'Sample Chart'. undefined method `column_chart' for #<#:0x007f02a68b8b70>

Kindly advise.

Thanks in Advance,
Dileep

**Comment by masweetman** [comment]
It could be because there aren't any issues with the criteria you selected. Are there any issues with the date range and the tracker type you selected?

**Comment by masweetman** [comment]
It appears you have not installed the chartkick gem, which is required for the plugin to work. Go to your redmine directory and run "bundle install". Let me know if you have any other issues!
